### ISSUE TITLE
ContentView.swift - File Missing

### ISSUE THREAD

**Issue by hardikthakkar54** [lividsubset3/soundcloud-carplay-ISO#1]
ContentView.swift file is missing can not check your code.

Thanks

**Comment by lividsubset3** [comment]
I have put this project on hold because the API from SoundCloud does not allow any more request to create custom apps. I plan on either talking with them directly and seeing if I can get a application code so I can continue. But I can add the ContentView.swift for your convenience.

**Comment by lividsubset3** [comment]
[ContentView.swift](https://github.com/lividsubset3/soundcloud-carplay-ISO/blob/main/IOS%20Dev/ISO_Dev/Shared/View%20Controllers/ContentView.swift)
